### ISSUE TITLE
Cannot complete ground school

### ISSUE THREAD

**Issue by Devirex** [mSparks43/XPlane-11-AutoATC-plugin#27]
Training the voice recognition works but exercise answers are not recognized. 
Phonetics training can be executed but progress is only displayed after restarting the app.
While training the status is always Trained [0/39] even after getting some matches. After restart the app status gets refreshed, Trained [39/39].
Phonetics exercise cannot be completed. UI shows Completed [ 0/25]
After giving right answer nothing happens, answer is not recognized.
Example:

Whats the phonetic word for the letter "J" ?

answer: juliett

But then nothing happens and answer is  not recognized as correct. Status is Completed[0/25] even after restarting the app.

**Comment by mSparks43** [comment]
I actually spotted this yesterday too, - fix one bug (ground school crashing) make a new one (not recalculating results)
Theoretically this is fixed in application version 0.8.7.049 which went live today but I need to clear all the results from my devices to be sure.
Ground school should also start filling up with more content this week.
