### ISSUE TITLE
missing replay support

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/XPlane-11-AutoATC-plugin#79]
aircraft play in realtime during replay and animations are broken

**Comment by JT8D-17** [comment]
Might be caused by AI aircraft being continuously injected into the sim regardless of the time multiplyer.

A local cache containing 2 minutes worth of AI position and animation data (to be filled in parallel with the real time data from the server) could solve this. Communications should be muted during replay as storing these is not feasible.

**Comment by mSparks43** [comment]
This is a bug with XPlane replay code, it seems there's no way to fix it for XP11.
