### ISSUE TITLE
Mac OS Plane Plugin Error

### ISSUE THREAD

**Issue by sr7171** [mSparks43/XPlane-11-AutoATC-plugin#86]
Hi,
    I am using XPlane 11.50 beta on Mac OS 10.13.6. I don't see the AutoATC 0.9.4.3 plugin in the plugin menu of XPlane. The log shows the following. Any suggested solutions appreciated.

dlerror:dlopen(/Users/stephen2/Desktop/X-Plane 11/Resources/plugins/AutoATC/64/mac.xpl, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/stephen2/Desktop/X-Plane 11/Resources/plugins/AutoATC/64/mac.xpl (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/stephen2/Desktop/X-Plane 11/Resources/plugins/AutoATC/64/mac.xpl 

Best regards

Steve

**Comment by mSparks43** [comment]
Hi Steve,
The latest mac build was compiled on Catalina (which is probably a bad idea, since it's struggling to run on Catalina..)

Since its missing a Darwin reference, I assume this is High Sierra or Mojave?
I don't have access to earlier macOS versions, probably the simplest solution is to compile it if possible?

There is an xcode project included in the source release.

**Comment by sr7171** [comment]
Hi,
    thanks for the response. I recompiled it on MacOS10.13.6. Works now.

Much appreciated

Steve
