### ISSUE TITLE
flight plan

### ISSUE THREAD

**Issue by bad2424** [mSparks43/XPlane-11-AutoATC-plugin#96]
hey i am having troubles filing flight plans. mainly telling me my EET time is too short and too long in the same error message.

**Comment by mSparks43** [comment]
The confusing message is a spelling error.
It's failing because it believes the duration of the flight will take longer than you entered (time too short)
And that the airframe you are filing with doesn't have sufficient range (distance too long)

which airframe are you filing with and whats the route?
